spring.application.name=Project-Backend

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8000
jwt.key=${JWT_KEY}

scalar.enabled=true
scalar.url=/api-docs
scalar.path=/docs

spring.threads.virtual.enabled=true